#!/usr/bin/env python3
"""Five-panel occupancy heatmaps as paper figures.

One PDF per setup: the five scheduling configurations stacked on a shared time axis, styled
like the two-panel figure.  The figures carry no text beyond their axes and the panel letters
(a)...(e); the graph's shape and every panel's T/T* are printed to stdout, ready to be worked
into a caption.

    python scripts/ablation/plot_heatmap_grid.py \\
        --setups tolokers-2:gat_v2:forward:128:0.99 ogbn-arxiv:gat_v2:forward:128:0.99 \\
        --cost-model cost_models.json --sms 108 --memory-bandwidth-gbps 2039 \\
        --out-dir reports/figures

--tex additionally writes the LaTeX: a legend mapping the letters to configurations, the
definition of T/T*, and a captioned figure environment per setup.  Off unless asked for.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import numpy as np

sys.path.append(str(Path(__file__).resolve().parent.parent.parent))
sys.path.append(str(Path(__file__).resolve().parent))

from plot_heatmap_pair import run_panel  # noqa: E402
from plot_launch_modes import bin_columns  # noqa: E402
from simulate_load_imbalance import (  # noqa: E402
    add_common_arguments,
    anchor_tick,
    load_degrees,
    resolve_cost_model,
    resolve_heavy_slice,
)

from skewgnn.simulation import bandwidth_cap_from_hardware  # noqa: E402

# The five configurations, in the order the paper builds the argument: start degree-agnostic,
# add bucketing, add slicing, then overlap the buckets, then both.
PANELS = [
    ("single", 0.0, "one kernel over every node, no degree bucketing"),
    ("sequential", 0.0, "heavy and light buckets, launched one after the other"),
    ("sequential", 8.0, "as (b), with the heavy bucket cut into edge slices and merged"),
    ("concurrent", 0.0, "heavy and light buckets launched concurrently"),
    ("concurrent", 8.0, "as (d), with edge slicing"),
]
LETTERS = ["(a)", "(b)", "(c)", "(d)", "(e)"]

PREAMBLE = r"""% ---------------------------------------------------------------------------
% Generated by scripts/ablation/plot_heatmap_grid.py -- do not edit by hand.
% Requires \usepackage{graphicx} and \usepackage{amsmath} in the document preamble.
% ---------------------------------------------------------------------------

\section{Scheduling configurations}
\label{sec:configurations}

Each figure below shows the same workload under five scheduling configurations.
Panel letters are fixed throughout:

PANEL_LEGEND_GOES_HERE

Colour gives utilization: the fraction of an SM's block slots that are occupied
at a given instant, so the darkest shade means every slot is busy and the
lightest means the SM stands idle. It counts slots, not warps, and is therefore
not the same quantity a profiler reports under that name.
The horizontal axis is the simulated cycle count; all five panels share
it, so a configuration that finishes earlier ends further to the left. The
hatched region marks the interval after a configuration has finished, during
which the remaining panels are still running; the solid rule marks the instant
the last block retires.

\paragraph{The ratio $T/T^{*}$.}
$T$ is the makespan: the cycle at which the last block of the configuration
retires. $T^{*}$ is the shortest makespan the same work could possibly achieve
on the same machine, taken as the largest of three lower bounds:

\begin{equation}
T^{*} = \max\!\left(
  \underbrace{\frac{1}{S}\sum_{j}\frac{c_j}{B_j}}_{\text{slots}},\;
  \underbrace{\frac{W}{\beta_{\mathrm{mem}}}}_{\text{bandwidth}},\;
  \underbrace{\max_j c_j}_{\text{critical path}}
\right)
\label{eq:tstar}
\end{equation}

where $c_j$ is the cost of block $j$ in cycles, $B_j$ the number of blocks of its
kernel that are resident per SM, $S$ the number of SMs, $W$ the total work and
$\beta_{\mathrm{mem}}$ the sustained row-fetch rate. The slot term is the work
spread perfectly over every block slot; the bandwidth term is the floor imposed
by memory; the critical-path term is the single most expensive block, which no
amount of parallelism can shorten unless that block is itself split.

$T/T^{*}\!\ge\!1$ by construction. A value of $1.0$ means the configuration is
already at the floor and only a different decomposition could help; larger
values measure how much of the machine the schedule wastes. Which of the three
bounds attains the maximum is reported per panel, and it is the actionable part:
when the critical path binds, the run lasts as long as one vertex and no launch
policy can change that, which is precisely what edge slicing addresses.

"""

STANDALONE = r"""%% Throwaway wrapper for previewing the generated figures on their own.
%% Compile next to the PDFs:  pdflatex preview.tex
%% The paper itself should \input the generated file instead, not this one.
\documentclass[10pt]{article}
\usepackage[a4paper,margin=20mm]{geometry}
\usepackage{graphicx}
\usepackage{amsmath}
\begin{document}
\input{GENERATED_TEX_NAME}
\end{document}
"""

FIGURE = r"""
\begin{figure}[t]
\centering
\includegraphics[width=\linewidth]{%(path)s}
\caption{%(caption)s}
\label{fig:%(label)s}
\end{figure}
"""


def tex_escape(text: str) -> str:
    """Escape the characters that actually occur in dataset and kernel names."""
    for char in "_&%#":
        text = text.replace(char, "\\" + char)
    return text


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    add_common_arguments(parser)
    parser.add_argument(
        "--setups",
        nargs="+",
        required=True,
        help="graph:conv:pass:head_dim:quantile, one per figure",
    )
    parser.add_argument("--out-dir", type=Path, default=Path("reports/figures"))
    parser.add_argument(
        "--tex",
        type=Path,
        default=None,
        help="Write LaTeX here: the panel legend, the definition of T/T* and a caption per "
        "figure. Omitted by default, in which case only the PDFs are produced",
    )
    parser.add_argument("--graphics-prefix", default="", help="Path prefix written into \\includegraphics")
    parser.add_argument("--max-columns", type=int, default=1600)
    parser.add_argument("--cmap", default="summer_r")
    parser.add_argument("--hatch", default="/")
    parser.add_argument("--hatch-linewidth", type=float, default=0.4)
    parser.add_argument("--end-line-width", type=float, default=1.8)
    parser.add_argument("--end-line-color", default="black")
    parser.add_argument("--xlabel", default="Simulated cycles")
    parser.add_argument("--ylabel", default="SM index")
    parser.add_argument("--colorbar-label", default="Utilization")
    parser.add_argument("--label-size", type=float, default=9.0)
    parser.add_argument("--width", type=float, default=7.0, help="Figure width in inches")
    parser.add_argument("--panel-height", type=float, default=0.62, help="Height of one heatmap in inches")
    parser.add_argument("--usetex", action="store_true", help="Render axis text with LaTeX; needs a TeX install")
    parser.add_argument(
        "--standalone",
        action="store_true",
        help="Also write preview.tex next to the figures: a minimal document that inputs the "
        "generated file, so the result can be compiled and looked at without the paper",
    )
    return parser.parse_args()


def plot(path: Path, results, num_sms: int, args: argparse.Namespace) -> None:
    os.environ.setdefault("MPLCONFIGDIR", str(path.parent / ".matplotlib"))
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    matplotlib.rcParams["hatch.linewidth"] = args.hatch_linewidth
    if args.usetex:
        matplotlib.rcParams["text.usetex"] = True

    figure, axes = plt.subplots(
        len(results),
        1,
        figsize=(args.width, 0.6 + args.panel_height * len(results)),
        sharex=True,
        constrained_layout=True,
    )
    axes = np.atleast_1d(axes)
    span = max(r.makespan for r in results)

    tag_strip = (2.4 * args.label_size / 72) / args.width
    figure.get_layout_engine().set(rect=(tag_strip, 0, 1 - tag_strip, 1))

    idle = matplotlib.colormaps[args.cmap](0.0)
    image = None
    for axis, result in zip(axes, results):
        axis.set_facecolor(idle)
        image = axis.imshow(
            bin_columns(result.sm_utilisation, args.max_columns).T,
            aspect="auto",
            origin="lower",
            interpolation="nearest",
            cmap=args.cmap,
            vmin=0,
            vmax=1,
            extent=(0.0, float(result.makespan), 0.0, num_sms),
        )
        axis.set_xlim(0.0, float(span))
        if args.hatch and result.makespan < span:
            axis.add_patch(
                matplotlib.patches.Rectangle(
                    (result.makespan, 0),
                    span - result.makespan,
                    num_sms,
                    facecolor="white",
                    edgecolor="black",
                    hatch=args.hatch,
                    linewidth=0.0,
                )
            )
        if args.end_line_width > 0:
            axis.axvline(result.makespan, color=args.end_line_color, linewidth=args.end_line_width, zorder=5)
        axis.set_ylabel(args.ylabel, fontsize=args.label_size)
        axis.tick_params(labelsize=args.label_size - 2)
    axes[-1].set_xlabel(args.xlabel, fontsize=args.label_size)

    bar = figure.colorbar(image, ax=axes.tolist(), location="right", fraction=0.015, pad=0.015)
    bar.set_label(args.colorbar_label, fontsize=args.label_size)
    bar.ax.tick_params(labelsize=args.label_size - 2)

    figure.canvas.draw()
    for axis, letter in zip(axes, LETTERS):
        box = axis.get_position()
        figure.text(
            0.12 * tag_strip,
            (box.y0 + box.y1) / 2,
            letter,
            fontsize=args.label_size,
            fontweight="bold",
            va="center",
            ha="left",
        )
    figure.savefig(path)
    plt.close(figure)


def caption(setup: dict, results, slices: list[int], args: argparse.Namespace) -> str:
    """Graph shape, kernel cell and the T/T* of every panel, as one LaTeX paragraph."""
    degrees = setup["degrees"]
    ratios = " ".join(
        f"{letter}~{r.imbalance_ratio:.3f} ({r.binding_bound.replace('_', ' ')});"
        for letter, r in zip(LETTERS, results)
    ).rstrip(";")
    sliced = [s for s in slices if s > 0]
    slicing = f" Edge slices in (c) and (e) hold {sliced[0]:,} edges each." if sliced and len(set(sliced)) == 1 else ""
    return (
        f"Per-SM occupancy over time for \\textsf{{{tex_escape(setup['graph'])}}} "
        f"($N={len(degrees[0]):,}$ vertices, $E={int(degrees[0].sum()):,}$ edges, "
        f"mean degree ${degrees[0].mean():.1f}$, maximum degree ${int(degrees[0].max()):,}$, "
        f"skew ${degrees[0].max() / degrees[0].mean():.0f}\\times$), kernel "
        f"\\textsf{{{tex_escape(setup['conv'])}}} {setup['pass_name']} at head dimension "
        f"{setup['head_dim']}, on {args.sms} SMs. Utilization is the fraction of an SM's block "
        f"slots that are occupied at that instant: $1$ when every slot is busy, $0$ when the SM "
        f"stands idle. The heavy bucket is the top "
        f"{(1 - setup['quantile']) * 100:.0f}\\% of vertices by degree "
        f"({len(degrees[2]):,} of them).{slicing} "
        f"Ratios $T/T^{{*}}$, with the bound that attains the maximum in brackets: {ratios}."
    )


def main() -> int:
    args = parse_args()
    args.occupancies = [max(args.occupancies)]
    args.out_dir.mkdir(parents=True, exist_ok=True)
    # LaTeX is written only when asked for. The numbers a caption needs are printed per setup
    # either way, so the default run produces PDFs and nothing else.
    tex_path = args.tex
    blocks: list[str] = []
    if tex_path:
        # The preamble is literal LaTeX full of % comments, so it is assembled by substitution
        # on one marker rather than by %-formatting, which would choke on every comment line.
        legend = "\n".join(
            [r"\begin{description}"]
            + [f"\\item[{letter}] {description}" for letter, (_, _, description) in zip(LETTERS, PANELS)]
            + [r"\end{description}"]
        )
        blocks.append(PREAMBLE.replace("PANEL_LEGEND_GOES_HERE", legend))
        tex_path.write_text("".join(blocks))
        if args.standalone:
            preview = tex_path.with_name("preview.tex")
            preview.write_text(STANDALONE.replace("GENERATED_TEX_NAME", tex_path.name))
            print(f"wrote {preview}  (cd {tex_path.parent} && pdflatex preview.tex)\n")
    elif args.standalone:
        print("--standalone needs --tex; nothing to wrap, ignoring it\n", file=sys.stderr)

    for spec in args.setups:
        graph, conv, pass_name, head_dim, quantile = spec.split(":")
        args.dataset, args.conv, args.pass_name = graph, conv, pass_name
        args.head_dim, args.quantile = int(head_dim), float(quantile)

        print(f"=== {spec}")
        cost_model, fit, _ = resolve_cost_model(args)
        degrees = load_degrees(args)
        # Everything a caption would say about the graph, so the run is self-sufficient when
        # no LaTeX is being written.
        all_degrees = degrees[0]
        print(
            f"  N={len(all_degrees):,} E={int(all_degrees.sum()):,} "
            f"mean deg={all_degrees.mean():.1f} max deg={int(all_degrees.max()):,} "
            f"skew={all_degrees.max() / all_degrees.mean():.0f}x heavy={len(degrees[2]):,}"
        )
        bandwidth_cap = bandwidth_cap_from_hardware(
            args.memory_bandwidth_gbps, args.feature_dim, args.dtype_bytes, args.memory_latency_ns
        )
        tick_ns, _ = anchor_tick(args, cost_model, fit, degrees, bandwidth_cap)

        results, slices = [], []
        for letter, (mode, blocks_per_sm, _) in zip(LETTERS, PANELS):
            slices.append(resolve_heavy_slice(0, blocks_per_sm, degrees[2], args.sms))
            result = run_panel(args, cost_model, degrees, bandwidth_cap, tick_ns, mode, blocks_per_sm)
            results.append(result)
            print(
                f"  {letter} {mode}{' + split-K' if blocks_per_sm else '':<10} "
                f"T={result.makespan:>9,} T*={result.perfect_packing_time:>10,.1f} "
                f"T/T*={result.imbalance_ratio:.3f} ({result.binding_bound})"
            )

        stem = f"{graph}-{conv}-{pass_name}-d{head_dim}-q{str(quantile)[2:]}"
        path = args.out_dir / f"{stem}.pdf"
        plot(path, results, args.sms, args)
        print(f"  wrote {path}")

        setup = {
            "graph": graph,
            "conv": conv,
            "pass_name": pass_name,
            "head_dim": head_dim,
            "quantile": float(quantile),
            "degrees": degrees,
        }
        if tex_path:
            blocks.append(
                FIGURE
                % {
                    "path": f"{args.graphics_prefix}{path.name}",
                    "caption": caption(setup, results, slices, args),
                    "label": stem,
                }
            )
            # Rewritten after every setup, not once at the end: a full grid takes most of a
            # day, and an interrupted run would otherwise leave the PDFs without the captions
            # that carry their T/T*, which cannot be recovered without simulating again.
            tex_path.write_text("".join(blocks))

    if tex_path:
        print(f"\nwrote {tex_path}  ({len(blocks) - 1} figure(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
