architecture: node_classifier

encoder:
  layers:
    - layer_type: residual_block
      conv_type: gat_v2
      backend: dgl
      in_channels: auto
      out_channels: 16
      heads: 8
      norm: batch
      activation: elu
      dropout: 0.6
      residual: false
      conv_kwargs: {}
    - layer_type: residual_block
      conv_type: gat_v2
      backend: dgl
      in_channels: auto
      out_channels: 7
      heads: 1
      norm: none
      activation: none
      dropout: 0.0
      residual: false
      conv_kwargs: {}
