architecture: node_classifier
num_classes: 0
dropout: 0.5

encoder:
  layers:
    - conv_type: sage
      backend: pyg
      in_channels: auto
      out_channels: 128
      norm: batch
      activation: relu
      dropout: 0.5
      residual: false
      conv_kwargs:
        aggr: mean         # 'mean' | 'sum' | 'max'
    - conv_type: sage
      backend: pyg
      in_channels: auto
      out_channels: 128
      norm: batch
      activation: relu
      dropout: 0.5
      residual: true
      conv_kwargs:
        aggr: mean
