# 2-layer GAT. Effective out of layer 1 = out_channels * heads (if concat=true).
architecture: node_classifier
num_classes: 0
dropout: 0.5

encoder:
  layers:
    - layer_type: residual_block
      conv_type: gt
      backend: dgl
      in_channels: auto
      out_channels: 16
      heads: 8
      norm: batch
      activation: elu
      dropout: 0.6
      residual: true
      conv_kwargs: {}
    - layer_type: residual_block
      conv_type: gt
      backend: dgl
      in_channels: auto
      out_channels: 7
      heads: 1
      norm: none
      activation: none
      dropout: 0.0
      residual: true
      conv_kwargs: {}