import numpy as np
import pytest

from turbo_gnn.calibration import Measurement, fit_cost_model
from turbo_gnn.simulation import (
    CostModel,
    KernelConfig,
    SimulationConfig,
    build_heavy_slices,
    build_slice_merge,
    simulate,
)

SHAPES = [(2_708, 13_264), (19_717, 108_365), (169_343, 1_335_586), (2_449_029, 126_167_309)]


def synthesise(launch_ns: float, ns_per_node: float, ns_per_edge: float, shapes) -> list[Measurement]:
    """Measurements generated by a known cost model, so a fit can be checked against truth."""
    return [
        Measurement(
            conv="gt",
            pass_name="forward",
            head_dim=128,
            graph=f"g{index}",
            num_nodes=num_nodes,
            num_edges=num_edges,
            time_ms=(launch_ns + ns_per_node * num_nodes + ns_per_edge * num_edges) / 1e6,
        )
        for index, (num_nodes, num_edges) in enumerate(shapes)
    ]


def test_fit_recovers_known_coefficients():
    fit = fit_cost_model(synthesise(30_000.0, 2.4, 0.4, SHAPES))
    assert fit.ns_per_tick == pytest.approx(0.4, rel=1e-6)
    assert fit.alpha == pytest.approx(6.0, rel=1e-6)
    assert fit.beta == 1.0
    assert fit.launch_overhead_ns == pytest.approx(30_000.0, rel=1e-6)
    assert fit.r2 == pytest.approx(1.0)
    assert fit.note == ""


def test_node_dominated_kernel_is_flagged_rather_than_calibrated():
    # min-aggregation's backward pass writes one gradient per node, so its time barely moves
    # with edge count and no alpha + beta * degree model describes it.
    fit = fit_cost_model(synthesise(5_000.0, 100.0, 0.001, SHAPES))
    assert fit.edge_time_share < 0.2
    assert not fit.trustworthy
    assert "node-dominated" in fit.note


def test_merge_waits_for_the_last_slice():
    # A separate launch is a global barrier: no merge block may start while a slice is running.
    cost_model = CostModel(alpha=0.0)
    workloads = {
        "heavy": build_heavy_slices([4_000], slice_size=1_000, cost_model=cost_model),
        "merge": build_slice_merge([4_000], slice_size=1_000, cost_model=cost_model),
    }
    kernels = {"heavy": KernelConfig("heavy", 4), "merge": KernelConfig("merge", 16)}
    gated = simulate(
        workloads, kernels, SimulationConfig(num_sms=132, bandwidth_cap=10_000, depends_on={"merge": "heavy"})
    )
    ungated = simulate(workloads, kernels, SimulationConfig(num_sms=132, bandwidth_cap=10_000))

    slices_done = int(np.flatnonzero(gated.active_blocks["heavy"] == 0)[0])
    assert gated.active_blocks["merge"][:slices_done].sum() == 0
    # Ungated, the merge runs alongside the slices and costs nothing; gated it is pure tail.
    assert ungated.makespan == 1_000
    assert gated.makespan == 1_004
