import json
import sys
from pathlib import Path

import pytest
import torch

from turbo_gnn.calibration import (
    Measurement,
    fit_all,
    fit_cost_model,
    load_cost_models,
    lookup,
    measurements_from_csv,
    measurements_from_kernel_benchmark_summary,
    save_cost_models,
)
from turbo_gnn.simulation import CostModel, KernelConfig, SimulationConfig, build_blocks, simulate


def synthesise(launch_ns: float, ns_per_node: float, ns_per_edge: float, shapes) -> list[Measurement]:
    """Measurements generated by a known cost model, so a fit can be checked against truth."""
    return [
        Measurement(
            conv="gt",
            pass_name="forward",
            head_dim=128,
            graph=f"g{index}",
            num_nodes=num_nodes,
            num_edges=num_edges,
            time_ms=(launch_ns + ns_per_node * num_nodes + ns_per_edge * num_edges) / 1e6,
        )
        for index, (num_nodes, num_edges) in enumerate(shapes)
    ]


SHAPES = [(2_708, 13_264), (19_717, 108_365), (169_343, 1_335_586), (2_449_029, 126_167_309)]


# --------------------------------------------------------------------------------------------
# The cost model itself
# --------------------------------------------------------------------------------------------


def test_default_cost_model_is_degree_plus_two():
    assert CostModel().block_cost([3]) == 5
    assert CostModel().block_cost([3, 4]) == 11
    assert build_blocks([3], "light")[0].cost == 5


def test_alpha_charges_the_prologue_once_per_node():
    assert CostModel(alpha=8.0).block_cost([3]) == 11
    assert CostModel(alpha=8.0).block_cost([3, 3]) == 22


def test_beta_scales_the_neighbour_loop():
    assert CostModel(alpha=2.0, beta=3.0).block_cost([4]) == 14


def test_fractional_costs_round_to_whole_ticks_and_never_vanish():
    assert CostModel(alpha=2.4).block_cost([1]) == 3
    assert CostModel(alpha=0.1).block_cost([0]) == 1


@pytest.mark.parametrize("kwargs", [{"alpha": -1.0}, {"beta": 0.0}, {"beta": -1.0}])
def test_cost_model_rejects_impossible_parameters(kwargs):
    with pytest.raises(ValueError):
        CostModel(**kwargs)


def test_lpt_balances_on_cost_not_on_degree():
    # With a heavy prologue, four degree-1 nodes cost more together than one degree-4 node, so
    # balancing on raw degree (which puts all four in one block) is wrong.
    degrees = [4, 1, 1, 1, 1]
    by_cost = build_blocks(degrees, "light", "lpt", num_blocks=2, cost_model=CostModel(alpha=10.0))
    assert sorted(len(block.node_ids) for block in by_cost) == [2, 3]
    assert max(block.cost for block in by_cost) == 33

    by_degree = build_blocks(degrees, "light", "lpt", num_blocks=2, cost_model=CostModel(alpha=0.0))
    assert sorted(len(block.node_ids) for block in by_degree) == [1, 4]


def test_calibrated_tick_turns_the_makespan_into_milliseconds():
    result = simulate(
        {"light": build_blocks([3], "light")},
        {"light": KernelConfig("light", 1)},
        SimulationConfig(num_sms=1, ns_per_tick=2.0),
    )
    assert result.makespan == 5
    assert result.predicted_ms == pytest.approx(5 * 2.0 / 1e6)
    assert result.summary()["predicted_ms"] == pytest.approx(5 * 2.0 / 1e6)


def test_uncalibrated_simulation_reports_no_wall_clock():
    result = simulate(
        {"light": build_blocks([3], "light")},
        {"light": KernelConfig("light", 1)},
        SimulationConfig(num_sms=1),
    )
    assert result.predicted_ms is None


# --------------------------------------------------------------------------------------------
# The fit
# --------------------------------------------------------------------------------------------


def test_fit_recovers_known_coefficients():
    fit = fit_cost_model(synthesise(30_000.0, 2.4, 0.4, SHAPES))
    assert fit.ns_per_tick == pytest.approx(0.4, rel=1e-6)
    assert fit.alpha == pytest.approx(6.0, rel=1e-6)
    assert fit.beta == 1.0
    assert fit.launch_overhead_ns == pytest.approx(30_000.0, rel=1e-6)
    assert fit.r2 == pytest.approx(1.0)
    assert fit.note == ""


def test_launch_overhead_is_separated_from_the_per_node_cost():
    # Overhead dominates the small graphs; charging it to alpha is what inflates the fit.
    measurements = synthesise(200_000.0, 10.0, 0.5, SHAPES)
    corrected = fit_cost_model(measurements)
    absorbed = fit_cost_model(measurements, fit_launch_overhead=False)
    assert corrected.alpha == pytest.approx(20.0, rel=1e-6)
    assert corrected.median_rel_error < 1e-9
    assert absorbed.alpha > 1.5 * corrected.alpha
    assert absorbed.median_rel_error > 0.05


def test_relative_weighting_is_not_dominated_by_the_largest_graph():
    measurements = synthesise(5_000.0, 30.0, 0.5, SHAPES)
    perturbed = [
        Measurement(**{**m.__dict__, "time_ms": m.time_ms * (1.5 if m.num_edges == 126_167_309 else 1.0)})
        for m in measurements
    ]
    relative = fit_cost_model(perturbed, "relative")
    uniform = fit_cost_model(perturbed, "uniform")
    assert relative.median_rel_error < uniform.median_rel_error
    assert max(error for _, error in uniform.worst_graphs) > max(error for _, error in relative.worst_graphs)


def test_coefficients_are_never_negative():
    # Adding nodes at a fixed edge count makes these launches *faster*, so an unconstrained fit
    # wants a negative per-node cost. Clamping it is what keeps alpha interpretable.
    shapes_and_times = [(1_000, 1_000, 0.100), (2_000, 1_000, 0.090), (1_000, 2_000, 0.200), (2_000, 2_000, 0.190)]
    measurements = [
        Measurement("gt", "forward", 128, f"g{i}", num_nodes=n, num_edges=e, time_ms=t)
        for i, (n, e, t) in enumerate(shapes_and_times)
    ]
    fit = fit_cost_model(measurements)
    assert fit.ns_per_node == 0.0
    assert fit.ns_per_edge > 0
    assert fit.alpha == 0.0
    assert "pinned to zero" in fit.note


def test_node_dominated_kernel_is_flagged_rather_than_calibrated():
    # min-aggregation's backward pass writes one gradient per node, so its time barely moves
    # with edge count and no alpha + beta * degree model describes it.
    fit = fit_cost_model(synthesise(5_000.0, 100.0, 0.001, SHAPES))
    assert fit.edge_time_share < 0.2
    assert not fit.trustworthy
    assert "node-dominated" in fit.note


def test_fit_needs_enough_measurements_for_its_coefficients():
    with pytest.raises(ValueError, match="need at least 3"):
        fit_cost_model(synthesise(0.0, 10.0, 0.5, SHAPES[:2]))


def test_fit_rejects_non_positive_times():
    measurements = synthesise(0.0, 10.0, 0.5, SHAPES)
    broken = [Measurement(**{**measurements[0].__dict__, "time_ms": 0.0}), *measurements[1:]]
    with pytest.raises(ValueError, match="positive"):
        fit_cost_model(broken)


def test_fit_all_groups_by_conv_pass_and_head_dim():
    measurements = synthesise(0.0, 10.0, 0.5, SHAPES)
    measurements += [Measurement(**{**m.__dict__, "conv": "gat_v2"}) for m in measurements]
    measurements += [Measurement(**{**m.__dict__, "head_dim": 256, "conv": "gt"}) for m in measurements[:2]]
    fits, skipped = fit_all(measurements)
    assert set(fits) == {"gt/forward/128", "gat_v2/forward/128"}
    assert "gt/forward/256" in skipped


# --------------------------------------------------------------------------------------------
# Loading and storing
# --------------------------------------------------------------------------------------------


SUMMARY_SNIPPET = """192 cells from 768 runs in reports/kernel-benchmarks
baseline = one_per_block in natural node order; self-loops added by the loader

### cora   geomean 1.387x   12/12 cells improved
    N=2,708 E=13,264 avg_deg=4.9 max_deg=169 heavy_fwd=29
    conv      dim      pass   baseline       best      x  winning config
    gt        128   forward     0.0834     0.0435   1.92  one_per_block+degree
    gt        256  backward     0.3207     0.2999   1.07  grid_stride+locality

### ogbn-arxiv   geomean 1.090x   11/12 cells improved
    N=169,343 E=1,335,586 avg_deg=7.9 max_deg=13,161 heavy_fwd=1,715
    conv      dim      pass   baseline       best      x  winning config
    gt        128   forward     1.2000     0.9000   1.33  grid_stride+locality

  if one configuration had to be the default, across all 192 cells
    config                            geomean   worst    best    >=1.0
    grid_stride+degree                  1.053    0.55    3.32   105/192
"""


def test_summary_parser_reads_the_baseline_column(tmp_path):
    path = tmp_path / "summary.txt"
    path.write_text(SUMMARY_SNIPPET)
    measurements = measurements_from_kernel_benchmark_summary(path)
    assert [(m.graph, m.conv, m.pass_name, m.head_dim, m.time_ms) for m in measurements] == [
        ("cora", "gt", "forward", 128, 0.0834),
        ("cora", "gt", "backward", 256, 0.3207),
        ("ogbn-arxiv", "gt", "forward", 128, 1.2000),
    ]
    assert (measurements[0].num_nodes, measurements[0].num_edges) == (2_708, 13_264)
    assert (measurements[2].num_nodes, measurements[2].num_edges) == (169_343, 1_335_586)


def test_summary_parser_ignores_the_trailing_configuration_table(tmp_path):
    path = tmp_path / "summary.txt"
    path.write_text(SUMMARY_SNIPPET)
    assert all(m.pass_name in ("forward", "backward") for m in measurements_from_kernel_benchmark_summary(path))
    assert len(measurements_from_kernel_benchmark_summary(path)) == 3


def test_csv_loader(tmp_path):
    path = tmp_path / "measurements.csv"
    path.write_text("conv,pass,head_dim,graph,num_nodes,num_edges,time_ms\ngt,forward,128,cora,2708,13264,0.0834\n")
    (measurement,) = measurements_from_csv(path)
    assert measurement.key == "gt/forward/128"
    assert measurement.time_ms == 0.0834


def test_cost_models_survive_a_round_trip(tmp_path):
    path = tmp_path / "cost_models.json"
    fits, _ = fit_all(synthesise(5_000.0, 30.0, 0.5, SHAPES))
    save_cost_models(path, fits, source="test", weighting="relative")
    reloaded = load_cost_models(path)
    assert reloaded == fits
    assert lookup(reloaded, "gt", "forward", 128).alpha == pytest.approx(60.0)


def test_loading_rejects_a_foreign_schema(tmp_path):
    path = tmp_path / "cost_models.json"
    path.write_text(json.dumps({"schema": "something-else", "models": {}}))
    with pytest.raises(ValueError, match="schema"):
        load_cost_models(path)


def test_lookup_names_the_cells_it_does_have():
    fits, _ = fit_all(synthesise(5_000.0, 30.0, 0.5, SHAPES))
    with pytest.raises(KeyError, match="gt/forward/128"):
        lookup(fits, "gt", "backward", 128)


# --------------------------------------------------------------------------------------------
# Pass selection in the sweep script
# --------------------------------------------------------------------------------------------


def test_backward_pass_simulates_the_transposed_graph():
    # --pass picks the cost model cell *and* the CSR. On a directed graph the two directions are
    # different workloads, so taking backward constants over forward degrees would be wrong.
    sys.path.append(str(Path(__file__).resolve().parents[2] / "scripts" / "ablation"))
    from simulate_load_imbalance import bucket_degrees

    class FakeGraph:
        # A path 0 -> 1 -> 2: in-degrees (0, 1, 1), out-degrees (1, 1, 0).
        forward_indptr = torch.tensor([0, 0, 1, 2])
        forward_light_nodes = torch.tensor([0, 1])
        forward_heavy_nodes = torch.tensor([2])
        backward_indptr = torch.tensor([0, 1, 2, 2])
        backward_light_nodes = torch.tensor([1, 2])
        backward_heavy_nodes = torch.tensor([0])

    forward_all, forward_light, forward_heavy = bucket_degrees(FakeGraph(), "forward")
    backward_all, backward_light, backward_heavy = bucket_degrees(FakeGraph(), "backward")
    assert forward_all.tolist() == [0, 1, 1]
    assert backward_all.tolist() == [1, 1, 0]
    assert (forward_light.tolist(), forward_heavy.tolist()) == ([0, 1], [1])
    assert (backward_light.tolist(), backward_heavy.tolist()) == ([1, 0], [1])

    with pytest.raises(ValueError, match="unknown direction"):
        bucket_degrees(FakeGraph(), "sideways")
